/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.*;
import dto.Alumno;
import java.util.Date;
import javax.swing.JOptionPane;
import logicanegocio.logicadenegocio;

/**
 *
 * @author rodrigo valdes
 */
public class EncuestaAlta extends javax.swing.JDialog {
           private Alumno alumnoseleccion = null;
//events de los campos, dar de baja y filtrar, camoos obligatorios
           
    private Menu menu;

    /**
     * Creates new form EncuestaAlta
     */
    public EncuestaAlta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        menu = (Menu)parent;
        initComponents();
        jButtonAlta.addActionListener(new MiActionListener());
                                               
    }
 public EncuestaAlta(java.awt.Frame parent, boolean modal, Alumno alumnoseleccion) {
    super(parent, modal);
    this.alumnoseleccion = alumnoseleccion;
     initComponents();
    jTextFieldDNI.setText(alumnoseleccion.getDNI());
    jTextFieldNombre.setText(alumnoseleccion.getNombre());
    jTextFieldApellido1.setText(alumnoseleccion.getApellido1());
    jTextFieldApellido2.setText(alumnoseleccion.getApellido2());
    jTextFieldEmail.setText(alumnoseleccion.getEmail());
    jTextFieldTelefono.setText(alumnoseleccion.getTelefono());
    jTextFieldCP.setText(alumnoseleccion.getCP());
    jSpinnerUltFactura.setValue(alumnoseleccion.getFechaUltFactura());
    jSpinnerAlta.setValue(alumnoseleccion.getFechaAlta());
    jComboBoxProvincia.setSelectedItem(alumnoseleccion.getProvincia());
    jTextFieldCalle.setText(alumnoseleccion.getCalle());
    jTextFieldLocalidad.setText(alumnoseleccion.getLocalidad());
    
   
   
 }
        
                                               
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombre = new javax.swing.JLabel();
        jLabelApellido1 = new javax.swing.JLabel();
        jLabelAlta = new javax.swing.JLabel();
        jLabelProvincia = new javax.swing.JLabel();
        jComboBoxProvincia = new javax.swing.JComboBox<>();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido1 = new javax.swing.JTextField();
        jSpinnerAlta = new javax.swing.JSpinner();
        jButtonAlta = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelApellido2 = new javax.swing.JLabel();
        jTextFieldApellido2 = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldCP = new javax.swing.JTextField();
        jLabelCP = new javax.swing.JLabel();
        jSpinnerUltFactura = new javax.swing.JSpinner();
        jLabelFechaFactura = new javax.swing.JLabel();
        jLabelDNI = new javax.swing.JLabel();
        jTextFieldDNI = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCalle = new javax.swing.JTextField();
        jTextFieldLocalidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jLabelNombre.setText("Nombre:");

        jLabelApellido1.setText("Apellido1:");

        jLabelAlta.setText("Fecha de alta:");

        jLabelProvincia.setText("Provincia:");

        jComboBoxProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asturias", "Cantabria", "León", "Vigo" }));
        jComboBoxProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProvinciaActionPerformed(evt);
            }
        });

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jTextFieldApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellido1ActionPerformed(evt);
            }
        });

        jSpinnerAlta.setModel(new javax.swing.SpinnerDateModel());

        jButtonAlta.setText("Dar de alta");
        jButtonAlta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAltaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAltaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAltaMouseExited(evt);
            }
        });
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelApellido2.setText("Apellido2:");

        jTextFieldApellido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellido2ActionPerformed(evt);
            }
        });

        jLabelTelefono.setText("Teléfono:");

        jLabelEmail.setText("Email:");

        jLabelCP.setText("CP:");

        jSpinnerUltFactura.setModel(new javax.swing.SpinnerDateModel());

        jLabelFechaFactura.setText("Fecha de última facturación:");

        jLabelDNI.setText("DNI:");

        jLabel1.setText("Calle:");

        jLabel2.setText("Localidad:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonAlta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelApellido1)
                .addContainerGap(146, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelFechaFactura)
                                .addComponent(jLabelAlta)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelApellido2)
                                        .addComponent(jLabelTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelProvincia, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabelEmail)
                                    .addComponent(jLabelCP, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGap(18, 18, 18))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabelNombre)
                            .addGap(18, 18, 18)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(106, 106, 106)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldLocalidad)
                    .addComponent(jTextFieldCalle)
                    .addComponent(jTextFieldDNI)
                    .addComponent(jTextFieldCP, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldEmail)
                    .addComponent(jTextFieldApellido2)
                    .addComponent(jSpinnerAlta)
                    .addComponent(jTextFieldNombre)
                    .addComponent(jTextFieldApellido1)
                    .addComponent(jSpinnerUltFactura, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxProvincia, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabelAlta, jLabelApellido1, jLabelApellido2, jLabelCP, jLabelEmail, jLabelFechaFactura, jLabelNombre, jLabelProvincia, jLabelTelefono});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelApellido1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellido2)
                    .addComponent(jTextFieldApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelefono))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProvincia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCP))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinnerAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFechaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerUltFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonAlta, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCancelar)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBoxProvincia, jSpinnerAlta, jSpinnerUltFactura, jTextFieldApellido1, jTextFieldApellido2, jTextFieldCP, jTextFieldEmail, jTextFieldNombre, jTextFieldTelefono});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProvinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProvinciaActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed

   
    }//GEN-LAST:event_jTextFieldNombreActionPerformed
  private boolean validarFormulario () {
if ((jTextFieldDNI.getText () == null) ||("".equals (jTextFieldDNI.getText())))
{
JOptionPane.showMessageDialog (this, "El campo nombre no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
return false;
}
if ((jTextFieldNombre.getText () == null) ||("".equals (jTextFieldNombre.getText())))
{
JOptionPane.showMessageDialog (this, "El campo nombre no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
return false;
}
if ((jTextFieldApellido1.getText() == null) ||("".equals(jTextFieldApellido1.getText ())))
{
JOptionPane.showMessageDialog (this, "El campo apellido1 no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
return false;
}
if ((jTextFieldApellido2.getText() == null) ||("".equals(jTextFieldApellido2.getText ())))
{
JOptionPane.showMessageDialog (this, "El campo apellido2 no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
return false;
}
if ((jTextFieldEmail.getText() == null) ||("".equals(jTextFieldEmail.getText ())))
{
JOptionPane.showMessageDialog (this, "El campo e-mail no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
return false;
}
if ((jTextFieldCP.getText() == null) ||("".equals(jTextFieldCP.getText ())))
{
JOptionPane.showMessageDialog (this, "El campo del código postal no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
return false;
}
if ((jTextFieldCalle.getText() == null) ||("".equals(jTextFieldCalle.getText ())))
{
JOptionPane.showMessageDialog (this, "El campo de la calle no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
return false;
}
if ((jTextFieldLocalidad.getText() == null) ||("".equals(jTextFieldLocalidad.getText ())))
{
JOptionPane.showMessageDialog (this, "El campo de la localidad no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
return false;
}
return true;
}

    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed
    if(validarFormulario()) {
    String DNI = jTextFieldDNI.getText();
    String nombre = jTextFieldNombre.getText();
    String apellido1 = jTextFieldApellido1.getText();
    String apellido2 = jTextFieldApellido2.getText();
    String telefono = jTextFieldTelefono.getText();
    String email = jTextFieldEmail.getText();
    String CP = jTextFieldCP.getText();
    Date fechaAlta = (Date)jSpinnerAlta.getValue();
    Date fechaultfacturacion = (Date)jSpinnerUltFactura.getValue();
    String provincia = (String)jComboBoxProvincia.getSelectedItem();
    String calle = jTextFieldCalle.getText();
    String localidad = jTextFieldLocalidad.getText();
    
    
   // se crea doble(duplicado)
    
    if(alumnoseleccion == null) {
         Alumno alumno = new Alumno(DNI, nombre, apellido1, apellido2, provincia, telefono, email, CP, fechaAlta, fechaultfacturacion, calle, localidad);
            logicadenegocio.AniadirAlumno(alumno);

    } else {
        alumnoseleccion.setDNI(DNI);
        alumnoseleccion.setNombre(nombre);
        alumnoseleccion.setApellido1(apellido1);
        alumnoseleccion.setApellido2(apellido2);
        alumnoseleccion.setTelefono(telefono);
        alumnoseleccion.setEmail(email);
        alumnoseleccion.setCP(CP);
        alumnoseleccion.setFechaAlta((Date)jSpinnerAlta.getValue());
        alumnoseleccion.setFechaUltFactura(fechaultfacturacion);
        alumnoseleccion.setProvincia((String)jComboBoxProvincia.getSelectedItem());
        alumnoseleccion.setCalle(calle);
        alumnoseleccion.setLocalidad(localidad);
          JOptionPane.showConfirmDialog(null, "Los datos del alumno serán modificados para siempre. ¿Está seguro?",
                "Confirmación modificación", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
    }
    
    setVisible(false);
   
 }
    }//GEN-LAST:event_jButtonAltaActionPerformed

   
    private void jButtonAltaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAltaMouseEntered
        // TODO add your handling code here:
    jButtonAlta.setToolTipText("Guarda la información haciendo click.");
    jButtonAlta.setBackground((java.awt.Color.blue));
    }//GEN-LAST:event_jButtonAltaMouseEntered

    private void jButtonAltaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAltaMouseExited
        // TODO add your handling code here:
         jButtonAlta.setBackground((java.awt.Color.white));
    }//GEN-LAST:event_jButtonAltaMouseExited

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

        if(evt.getSource() == jLabelNombre){
            jLabelNombre.setText("<--Escribe tu nombre.");
        }
        if(evt.getSource() == jLabelApellido1){
            jLabelApellido1.setText("<--Escribe tu primer apellido.");
        }
    }//GEN-LAST:event_formFocusGained

    private void jButtonAltaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAltaMouseClicked

    }//GEN-LAST:event_jButtonAltaMouseClicked

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
    dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellido1ActionPerformed

    private void jTextFieldApellido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellido2ActionPerformed


  

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JComboBox<String> jComboBoxProvincia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAlta;
    private javax.swing.JLabel jLabelApellido1;
    private javax.swing.JLabel jLabelApellido2;
    private javax.swing.JLabel jLabelCP;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFechaFactura;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelProvincia;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JSpinner jSpinnerAlta;
    private javax.swing.JSpinner jSpinnerUltFactura;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldApellido2;
    private javax.swing.JTextField jTextFieldCP;
    private javax.swing.JTextField jTextFieldCalle;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldLocalidad;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
